name: Java CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Compile the application
      run: javac Main.java

    - name: Run the application
      run: java Main

    - name: Test the add method
      run: |
        echo "Testing the add method"
        javac Main.java
        expected=5
        result=$(java Main 2 3)
        if [ "$result" -ne "$expected" ]; then
          echo "Test failed: expected $expected but got $result"
          exit 1
        else
          echo "Test passed: $result is correct"
        fi
 